# GLOBAL variables: which can be consumed by all charts
# images, contrail_env, contrail_env_vrouter_dpdk, contrail_env_vrouter_kernel
global:
  # section to configure images for all containers
  images:
    tags:
      # You can override container names here using container name as a tag. Just replace '-' in container name to '_'. See example:
      #   contrail_external_kafka: "docker.io/opencontrailnightly/contrail-external-kafka:master-latest"
      dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0

  # contrail_env section for all containers
  contrail_env:
    CONTROLLER_NODES: 10.0.2.15
    CLOUD_ORCHESTRATOR: kubernetes
    AAA_MODE: no-auth
    JVM_EXTRA_OPTS: "-Xms1g -Xmx2g"
    KUBERNETES_PUBLIC_FIP_POOL: "{'project' : 'k8s-default', 'domain': 'default-domain', 'name': '__fip_pool_public__' , 'network' : '__public__'}"
  # Values from this section will be passed as ENV variables to all provisioner containers
  default_env:
    # VXLAN_VN_ID_MODE: "automatic"
  node:
    host_os: centos

# Chart level variables like manifests, labels which are local to subchart
# Can be updated from the parent chart like below
# Example of overriding values of subchart, where contrail-vrouter is name of the subchart
contrail-vrouter:
  manifests:
    configmap_vrouter_keystone: false
    job_kubernetes_cni_init: true

contrail-analytics:
  manifests:
    configmap_analytics_keystone: false
    configmap_controller_rabbitmq: false

contrail-controller:
  manifests:
    configmap_controller_keystone: false
    daemonset_kube_manager: true
    configmap_controller_rabbitmq: false

contrail-thirdparty:
  manifests:
    configmap_thirdparty_keystone: false

